version: '3'

services:
  alex:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    # ports:
    #   - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./volume:/data/db
